backend/urls.py
from django.conf.urls import include, url
#from django.contrib.auth import views as auth_views
import frontend
from . import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.decorators import login_required

app_name = 'backend'
urlpatterns = [
	url(r'^backend/$', views.backend_home, name='backend_home'),
	url(r'^backend/operations$', views.OperationsPageView.as_view(), name='operations'),
	url(r'^backend/operations/restaurants$', views.backend_ops_restaurants_PageView.as_view(), name='backend_ops_restaurants'),
	url(r'^backend/operations/attractions$', views.backend_ops_attractions_PageView.as_view(), name='backend_ops_attractions'),
	url(r'^backend/operations/apartments$', views.backend_ops_apartments, name='backend_ops_apartments'),
	url(r'^backend/operations/landing$', views.backend_ops_landing, name='backend_ops_landing'),
	url(r'^backend/operations/about$', views.backend_ops_about, name='backend_ops_about'),
	url(r'^backend/operations/contact$', views.backend_ops_contact, name='backend_ops_contact'),
	url(r'^backend/operations/users$', views.staff_accounts_abuse, name='staff_accounts_abuse'),
	# url(r'^backend/operations/landing$', views.backend_ops_landing_PageView.as_view(), name='backend_ops_landing'),
	# url(r'^backend/operations/contact$', views.backend_ops_contact_PageView.as_view(), name='backend_ops_contact'),
	# url(r'^backend/operations/about$', views.backend_ops_about_PageView.as_view(), name='backend_ops_about'),
	# url(r'^backend/operations/deals$', views.backend_ops_apartments_PageView.as_view(), name='backend_ops_deals'),
	# url(r'^backend/operations/apartments$', views.backend_ops_apartments_PageView.as_view(), name='backend_ops_apartments'),


	url(r'^backend/landing/add_restaurant$', views.landing_new_restaurant, name='landing_new_restaurant'),
	url(r'^backend/landing/add_attraction$', views.landing_new_attraction, name='landing_new_attraction'),
	url(r'^backend/landing/add_apartment$', views.landing_new_apartment, name='landing_new_apartment'),

	url(r'^backend/landing/restaurant/(?P<pk>\d+)/$', views.landing_restaurant_detail, name='landing_restaurant_detail'),
	url(r'^backend/landing/attraction/(?P<pk>\d+)/$', views.landing_attraction_detail, name='landing_attraction_detail'),
	url(r'^backend/landing/apartment/(?P<pk>\d+)/$', views.landing_apartment_detail, name='landing_apartment_detail'),

    url(r'^backend/landing/restaurants/(?P<pk>\d+)/edit/$', login_required(views.landing_restaurant_edit), name='landing_restaurant_edit'),
    url(r'^backend/landing/attraction/(?P<pk>\d+)/edit/$', login_required(views.landing_attraction_edit), name='landing_attraction_edit'),
    url(r'^backend/landing/apartment/(?P<pk>\d+)/edit/$', login_required(views.landing_apartment_edit), name='landing_apartment_edit'),

	url(r'^backend/landing/restaurants/(?P<pk>\d+)/remove/$', login_required(views.landing_restaurant_remove), name='landing_restaurant_remove'),
	url(r'^backend/landing/attraction/(?P<pk>\d+)/remove/$', login_required(views.landing_attraction_remove), name='landing_attraction_remove'),
	url(r'^backend/landing/apartment/(?P<pk>\d+)/remove/$', login_required(views.landing_apartment_remove), name='landing_apartment_remove'),


	url(r'^backend/about/add_page_title$', views.about_new_pageTitle, name='about_new_pageTitle'),
	url(r'^backend/about/add_presentation$', views.about_new_presentation, name='about_new_presentation'),
	url(r'^backend/about/add_team_title$', views.about_new_teamTitle, name='about_new_teamTitle'),
	url(r'^backend/about/add_member1$', views.about_new_member1, name='about_new_member1'),
	url(r'^backend/about/add_member2$', views.about_new_member2, name='about_new_member2'),
	url(r'^backend/about/add_member3$', views.about_new_member3, name='about_new_member3'),

	url(r'^backend/about/page_title/(?P<pk>\d+)/$', views.about_pageTitle_detail, name='about_pageTitle_detail'),
	url(r'^backend/about/presentation/(?P<pk>\d+)/$', views.about_presentation_detail, name='about_presentation_detail'),
	url(r'^backend/about/team_title/(?P<pk>\d+)/$', views.about_teamTitle_detail, name='about_teamTitle_detail'),
	url(r'^backend/about/member1/(?P<pk>\d+)/$', views.about_member1_detail, name='about_memberOne_detail'),
	url(r'^backend/about/member2/(?P<pk>\d+)/$', views.about_member2_detail, name='about_memberTwo_detail'),
	url(r'^backend/about/member3/(?P<pk>\d+)/$', views.about_member3_detail, name='about_memberThree_detail'),

	url(r'^backend/about/title/(?P<pk>\d+)/edit/$', login_required(views.about_pageTitle_edit), name='about_title_edit'),
	url(r'^backend/about/presentation/(?P<pk>\d+)/edit/$', login_required(views.about_presentation_edit), name='about_presentation_edit'),
	url(r'^backend/about/team/(?P<pk>\d+)/edit/$', login_required(views.about_teamTitle_edit), name='about_teamTitle_edit'),
	url(r'^backend/about/member1/(?P<pk>\d+)/edit/$', login_required(views.about_member1_edit), name='about_member1_edit'),
	url(r'^backend/about/member2/(?P<pk>\d+)/edit/$', login_required(views.about_member2_edit), name='about_member2_edit'),
	url(r'^backend/about/member3/(?P<pk>\d+)/edit/$', login_required(views.about_member3_edit), name='about_member3_edit'),

	url(r'^backend/about/title/(?P<pk>\d+)/remove/$', login_required(views.about_pageTitle_remove), name='about_title_remove'),
	url(r'^backend/about/presentation/(?P<pk>\d+)/remove/$', login_required(views.about_presentation_remove), name='about_presentation_remove'),
	url(r'^backend/about/team/(?P<pk>\d+)/remove/$', login_required(views.about_teamTitle_remove), name='about_teamTitle_remove'),
	url(r'^backend/about/member1/(?P<pk>\d+)/remove/$', login_required(views.about_member1_remove), name='about_member1_remove'),
	url(r'^backend/about/member2/(?P<pk>\d+)/remove/$', login_required(views.about_member2_remove), name='about_member2_remove'),
	url(r'^backend/about/member3/(?P<pk>\d+)/remove/$', login_required(views.about_member3_remove), name='about_member3_remove'),


	url(r'^backend/contact/add_header$', views.contact_new_header, name='contact_new_header'),
	url(r'^backend/contact/add_information$', views.contact_new_information, name='contact_new_information'),
	url(r'^backend/contact/add_address$', views.contact_new_address, name='contact_new_address'),

	url(r'^backend/contact/header/(?P<pk>\d+)/$', views.contact_header_detail, name='contact_header_detail'),
	url(r'^backend/contact/information/(?P<pk>\d+)/$', views.contact_information_detail, name='contact_information_detail'),
	url(r'^backend/contact/address/(?P<pk>\d+)/$', views.contact_address_detail, name='contact_address_detail'),

	url(r'^backend/contact/header/(?P<pk>\d+)/edit/$', login_required(views.contact_header_edit), name='contact_header_edit'),
	url(r'^backend/contact/information/(?P<pk>\d+)/edit/$', login_required(views.contact_information_edit), name='contact_information_edit'),
	url(r'^backend/contact/address/(?P<pk>\d+)/edit/$', login_required(views.contact_address_edit), name='contact_address_edit'),

	url(r'^backend/contact/header/(?P<pk>\d+)/remove/$', login_required(views.contact_header_remove), name='contact_header_remove'),
	url(r'^backend/contact/information/(?P<pk>\d+)/remove/$', login_required(views.contact_information_remove), name='contact_information_remove'),
	url(r'^backend/contact/address/(?P<pk>\d+)/remove/$', login_required(views.contact_address_remove), name='contact_address_remove'),	


	url(r'^backend/houses/add_house$', views.house_create, name='house_create'),
	url(r'^backend/houses/detail/(?P<pk>\d+)/$', views.house_details, name='house_details'),
	url(r'^backend/houses/edit/(?P<pk>\d+)/$', views.house_edit, name='house_edit'),
	url(r'^backend/houses/remove/(?P<pk>\d+)/$', views.house_remove, name='house_remove'),


	url(r'^backend/accounts/unban/(?P<pk>\d+)/$', login_required(views.staff_unban_user), name='staff_unban_user'),
	url(r'^backend/accounts/ban/(?P<pk>\d+)/$', login_required(views.staff_ban_user), name='staff_ban_user'),
	url(r'^backend/accounts/abuse$', login_required(views.staff_accounts_abuse), name='staff_accounts_abuse'),  
    url(r'^backend/accounts/delete$', login_required(views.to_del_user), name='staff_predel_user'),  
	url(r'^backend/accounts/(?P<pk>\d+)/delete/$', login_required(views.del_user), name='del_user'),  
	url(r'^backend/staff/list/$', login_required(views.staff_list), name='staff_list'),

    url(r'^signup/$', views.signup, name='signup'),


] 

easyhome/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from appApi import views
from appApi import models


router = routers.DefaultRouter()
router.register(r'users', views.UsersViewSet)
router.register(r'deal',views.DealViewSet)
router.register(r'attractions',views.AttractionsViewSet)
router.register(r'restaurant',views.RestaurantViewSet)
router.register(r'services',views.ServicesViewSet)
router.register(r'accomodations', views.AccomodationsViewSet)
router.register(r'reviews', views.ReviewsViewSet)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('backend.urls')),
    url(r'', include('frontend.urls')),
    url(r'api/', include(router.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'', views.AccomodationsListView, name='accomodations'),
    #url(r'',views.AccomodationsListView.as_view(), name="accomodations"),
   # url(r'^api/docs/', include('rest_framework_docs.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

frontend/urls.py
from django.conf.urls import include, url
#from django.contrib.auth import views as auth_views
import backend
from . import views
from django.contrib.auth.decorators import login_required
"""from rest_framework.schemas import get_schema_view
schema_view = get_schema_view(title='Pastebin API')"""

"""url(r'^$', views.frontend_home, name='frontend_home'),"""

app_name='frontend'
urlpatterns = [
	url(r'^search/',views.pageform,name="search"),
	url(r'^searchR/',views.pageformR,name="searchR"),
	url(r'^searchA/',views.pageformA,name="searchA"),
	url(r'^single/',views.single,name="single"),
	url(r'^singleA/',views.singleA,name="singleA"),
	url(r'^singleR/',views.singleR,name="singleR"),
	url(r'^ListR/',views.listAllRestaurants,name="ListR"),
	url(r'^ListA/',views.listAllAttractions,name="ListA"),
	url(r'^ListAcc/',views.listAllAccomodations,name="listAcc"),
	url(r'^home/$', views.frontend_home, name='frontend_home'),
	#url(r'^about$', views.AboutPageView.as_view(), name='AboutPageView'),
	url(r'^about$', views.frontend_about, name='frontend_about'),
	#url(r'^contact$', views.frontend_contact, name='frontend_contact'),
	url(r'^contact$', views.frontend_contact, name='frontend_contact'),


    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/profile', views.ProfilePageView.as_view(), name='profile'),

    url(r'^api/docs/', include('rest_framework_docs.urls')),

]

appApi/models.py
from django.db import models

class Reviews(models.Model):
    count = models.IntegerField()
    stars = models.IntegerField()

class Users(models.Model):
    first_name = models.CharField(max_length=100, blank=True, default='')
    last_name = models.CharField(max_length=100, blank=True, default='')
    email = models.EmailField(max_length=254,default='')
    location = models.CharField(max_length=100, blank=True, default='',unique = True)
    postal = models.CharField(max_length=100, blank=True, default='',unique = True)


class Services(models.Model):
    wifi = models.BooleanField(default=True)
    shower = models.BooleanField(default=True)
    kitchen = models.BooleanField(default=True)
    surveillanceCamera = models.BooleanField(default=True)
    HeatingSystem = models.BooleanField(default=True)
    Television = models.BooleanField(default=True)

class Accomodations(models.Model):
    title = models.CharField(max_length=100, blank=True, default='')
    address = models.CharField(max_length=100, blank=True, default='')
    description = models.TextField(default='')
    price = models.IntegerField()
    image = models.URLField()
    image2 = models.URLField()
    image3 = models.URLField()
    image4 = models.URLField()
    owner = models.ForeignKey(Users,on_delete=models.CASCADE)
    visibility = models.BooleanField(default=True)
    guests = models.IntegerField(default=1)
    bedrooms = models.IntegerField(default=1)
    beds = models.IntegerField(default=1)
    bathroom = models.IntegerField(default=1)
    services = models.ForeignKey(Services,null=False,on_delete=models.CASCADE)
    rules = models.TextField(default='')
    extraInfo = models.TextField(default='')
    city = models.CharField(max_length=100, blank=False, default='')
    kindOfHouse = models.CharField(max_length=100, blank=True, default='')
    reviews = models.ForeignKey(Reviews,on_delete=models.CASCADE)
    locationMap = models.TextField(default='')
    published_date = models.DateTimeField(blank=True, null=True)

class Restaurant(models.Model):
    name = models.CharField(max_length=100, blank=True, default='')
    description = models.TextField(default='')
    priceRange = models.CharField(max_length=100, blank=True, default='')
    address = models.CharField(max_length=100, blank=True, default='')
    image = models.URLField()
    image2 = models.URLField()
    image3 = models.URLField()
    city = models.CharField(max_length=100, blank=False, default='')
    link = models.URLField()
    locationMap = models.TextField()
    kindOfRestaurant=models.CharField(max_length=100, blank=False, default='')

class Attractions(models.Model):
    name = models.CharField(max_length=100, blank=True, default='')
    built = models.CharField(max_length=100, blank=True, default='')
    kindOfAttractions = models.CharField(max_length=100, blank=True, default='')
    title1 = models.CharField(max_length=100, blank=True, default='')
    title2 = models.CharField(max_length=100, blank=True, default='')
    title3 = models.CharField(max_length=100, blank=True, default='')
    description1 = models.TextField(default='')
    description2 = models.TextField(default='')
    description3 = models.TextField(default='')
    address = models.CharField(max_length=100, blank=True, default='')
    image = models.URLField()
    image2 = models.URLField()
    image3 = models.URLField()
    city = models.CharField(max_length=100, blank=False, default='')
    link = models.URLField()
    locationMap = models.TextField()
    published_date = models.DateTimeField(blank=True, null=True)
class Deal(models.Model):
    price = models.IntegerField()
    description = models.TextField()
    accomodations = models.ForeignKey(Accomodations,on_delete=models.CASCADE)
    attractions = models.ForeignKey(Attractions,on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant,on_delete=models.CASCADE)

frontend/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

appApi/views.py
from django.shortcuts import render
from appApi.serializers import UsersSerializer, AccomodationsSerializer,ReviewsSerializer,ServicesSerializer,AttractionsSerializer,RestaurantSerializer,DealSerializer
from rest_framework import viewsets
from appApi.models import Users,Reviews,Accomodations,Services,Attractions,Restaurant,Deal
import backend
from backend.models import *

class UsersViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Users.objects.all()
    serializer_class = UsersSerializer

"""import django_filters.rest_framework"""
from rest_framework import generics

from django.views.generic import ListView

# class AccomodationsListView(ListView):
#     model = Accomodations
#     template_name = 'frontend/templates/frontend/index.html'
#     context_object_name = 'accomodations'

def AccomodationsListView(request):
	restaurants = Restaurants.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	attractions = Attractions.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	apartments = Apartments.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	accomodations = Accomodations.objects.all()
	return render(request, 'appApi/accomodations_list.html', {'restaurants': restaurants, 'attractions': attractions, 'apartments':apartments, 'accomodations':accomodations})

class ReviewsViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Reviews.objects.all()
    serializer_class = ReviewsSerializer
class AccomodationsViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Accomodations.objects.all()
    serializer_class = AccomodationsSerializer
# Create your views here.

class ServicesViewSet(viewsets.ModelViewSet):
    queryset = Services.objects.all()
    serializer_class = ServicesSerializer

class RestaurantViewSet(viewsets.ModelViewSet):
    queryset = Restaurant.objects.all()
    serializer_class = RestaurantSerializer

class AttractionsViewSet(viewsets.ModelViewSet):
    queryset = Attractions.objects.all()
    serializer_class = AttractionsSerializer

class DealViewSet(viewsets.ModelViewSet):
    queryset = Deal.objects.all()
    serializer_class = DealSerializer

frontend/templates/appApi/accomodations_list.html
{% extends 'frontend/index.html' %}
{% load staticfiles %}

{% block content %}

<div class="contant">
	<div class="container">
		<div class="contant-main">
			  <div class="col-md-4 content-grid-1 bg-one">
			  	<div class="content-grid-text">
			  		{% for apartment in apartments %}
						<h3>{{ apartment.title }}</h3>
						<p>{{ apartment.text|linebreaksbr }}</p>
						<!-- <p>{{ section.text|safe }}</p> -->
					{% endfor %}
			  		
			  		 <div class=" ser-grid">
		   				<a href="#" class="hi-icon hi-icon-archive glyphicon glyphicon-home"> </a>
		   			  </div>
			  		<div class="contant-bwn">
							<form action="/search/" method="get">
							    <div class="search-wrapper">

									<input type="text" value="Type a City" class="search-field" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Type a City';}" name="name"/>
									<input type="submit" class="search-img" value="">

							    </div>

   								<button class="button push" type="submit" href="" style="" >View</button>

							</form>
			  		</div>
			  	</div>
			  </div>
			  <div class="col-md-4 content-grid-1 bg-two">
			  	<div class="content-grid-text">
			  		{% for attraction in attractions %}
						<h3>{{ attraction.title }}</h3>
						<p>{{ attraction.text|linebreaksbr }}</p>
						<!-- <p>{{ section.text|safe }}</p> -->
					{% endfor %}
			  		
			  		<div class=" ser-grid">
		   				<a href="#" class="hi-icon hi-icon-archive glyphicon"><i class="fa fa-university fa-2x" style="icon"aria-hidden="true"></i></a>
		   			  </div>
							<div class="contant-bwn">
								<form action="/searchA/" method="get">
								<div class="search-wrapper">

									<input type="text" value="Type a City" class="search-field" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Type a City';}" name="name"/>
									<input type="submit" class="search-img" value="">

								</div>
								<button class="button push" type="submit" href="" style="" >View</button>
							</form>
				  		</div>
			  	</div>
			  </div>
			  <div class="col-md-4 content-grid-3 bg-three">
			  	<div class="content-grid-text">
	  				{% for restaurant in restaurants %}
						<h3>{{ restaurant.title }}</h3>
						<p>{{ restaurant.text|linebreaksbr }}</p>
						<!-- <p>{{ section.text|safe }}</p> -->
					{% endfor %}
			  		
			  		<div class="ser-grid">
		   				<a href="#" class="hi-icon hi-icon-archive glyphicon glyphicon-cutlery"> </a>
		   			  </div>
			  		<div class="contant-bwn">
							<form action="/searchR/" method="get">
							<div class="search-wrapper">

								<input type="text" value="Type a City" class="search-field" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Type a City'; }" name="name"/>
								<input type="submit" class="search-img" value="">

							</div>
							<button class="button push" type="submit" href="" style="" >View</button>
						</form>
			  		</div>
			  	</div>
			  </div>
			<div class="clearfix"> </div>
			</div>
		</div>
</div>
<!--contact end here-->
<script>
		$(document).ready(function () {
		    size_li = $("#myList li").size();
		    x=4;
		    $('#myList li:lt('+x+')').show();
		    $('#loadMore').click(function () {
		        x= (x+4 <= size_li) ? x+4 : size_li;
		        $('#myList li:lt('+x+')').show();
		    });
		    $('#showLess').click(function () {
		        x=(x-4<0) ? 1 : x-4;
		        $('#myList li').not(':lt('+x+')').hide();
		    });
		});
	</script>

<!--feature grid start here-->
<div class="feature-grid">
	<div class="container">
		<div class="feature-grid-main">
			<h5>Top Rated Houses</h5>

		      <div class="load_more">
					 <ul id="myList">
						 	{% for a in accomodations %}
					    <!-- These are our grid blocks -->
					<form action="/single/" method="get">
					<li>

					<div class="l_g">



						<div class="col-md-3 fea-grid-1">

							<div class="fea-grid-top">
								<a href="{% url 'frontend:single' %}?id={{a.id}}"><img src={{a.image}} class="img-responsive"></img></a>
							</div>
							<div class="fea-grid-bottom">
								<h3 style="color:white;"><a href="{% url 'frontend:single' %}?id={{a.id}}">{{a.title}}</a></h3>

								<div class="fea-grid-left">
									<p>Rental from:</p>
									<p>City:</p>
									<p>Guests:</p>
								</div>
								<div class="fea-grid-right">
									<p>{{a.price}}&euro;</p>
									<p>{{a.city}}</p>
									<p>{{a.guests}}</p>
								</div>
								<div class="fea-grid-center">
									<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

									<span class="fa fa-star checked"></span>
									<span class="fa fa-star checked"></span>
									<span class="fa fa-star checked"></span>
									<span class="fa fa-star checked"></span>
									<span class="fa fa-star"></span>
									<p style="color:white">4.1 average based on 254 reviews.</p>
								</div>
								<div class="clearfix"> </div>
							</div>
						  <div class="clearfix"> </div>
						  </input>
						</div>


						</li>
					</form>
					{%endfor%}




				<div class="clearfix"> </div>

			</ul>

	<div id="loadMore">Load More</div>

	<div id="showLess">Show less</div>
		</div>
	</div>
</div>
</div>
<!--feature grid end here-->
<!--map start here-->
<div class="map">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2486.51974787438!2d5.488526115970238!3d51.44861312282034!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c6d8e08bdd34c1%3A0xc4a671b15dfb8dff!2sUniversit%C3%A0+tecnica+di+Eindhoven!5e0!3m2!1sit!2sin!4v1515013560872" frameborder="0" style="border:0" ></iframe>
</div>

{% endblock %}