backend/urls.py
from django.conf.urls import include, url
#from django.contrib.auth import views as auth_views
import frontend
from . import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.decorators import login_required

app_name = 'backend'
urlpatterns = [
	url(r'^backend/$', views.backend_home, name='backend_home'),
	url(r'^backend/operations$', views.OperationsPageView.as_view(), name='operations'),
	url(r'^backend/operations/restaurants$', views.backend_ops_restaurants_PageView.as_view(), name='backend_ops_restaurants'),
	url(r'^backend/operations/attractions$', views.backend_ops_attractions_PageView.as_view(), name='backend_ops_attractions'),
	url(r'^backend/operations/apartments$', views.backend_ops_apartments, name='backend_ops_apartments'),
	url(r'^backend/operations/landing$', views.backend_ops_landing, name='backend_ops_landing'),
	url(r'^backend/operations/about$', views.backend_ops_about, name='backend_ops_about'),
	url(r'^backend/operations/contact$', views.backend_ops_contact, name='backend_ops_contact'),
	url(r'^backend/operations/users$', views.staff_accounts_abuse, name='staff_accounts_abuse'),
	# url(r'^backend/operations/landing$', views.backend_ops_landing_PageView.as_view(), name='backend_ops_landing'),
	# url(r'^backend/operations/contact$', views.backend_ops_contact_PageView.as_view(), name='backend_ops_contact'),
	# url(r'^backend/operations/about$', views.backend_ops_about_PageView.as_view(), name='backend_ops_about'),
	# url(r'^backend/operations/deals$', views.backend_ops_apartments_PageView.as_view(), name='backend_ops_deals'),
	# url(r'^backend/operations/apartments$', views.backend_ops_apartments_PageView.as_view(), name='backend_ops_apartments'),


	url(r'^backend/landing/add_restaurant$', views.landing_new_restaurant, name='landing_new_restaurant'),
	url(r'^backend/landing/add_attraction$', views.landing_new_attraction, name='landing_new_attraction'),
	url(r'^backend/landing/add_apartment$', views.landing_new_apartment, name='landing_new_apartment'),

	url(r'^backend/landing/restaurant/(?P<pk>\d+)/$', views.landing_restaurant_detail, name='landing_restaurant_detail'),
	url(r'^backend/landing/attraction/(?P<pk>\d+)/$', views.landing_attraction_detail, name='landing_attraction_detail'),
	url(r'^backend/landing/apartment/(?P<pk>\d+)/$', views.landing_apartment_detail, name='landing_apartment_detail'),

    url(r'^backend/landing/restaurants/(?P<pk>\d+)/edit/$', login_required(views.landing_restaurant_edit), name='landing_restaurant_edit'),
    url(r'^backend/landing/attraction/(?P<pk>\d+)/edit/$', login_required(views.landing_attraction_edit), name='landing_attraction_edit'),
    url(r'^backend/landing/apartment/(?P<pk>\d+)/edit/$', login_required(views.landing_apartment_edit), name='landing_apartment_edit'),

	url(r'^backend/landing/restaurants/(?P<pk>\d+)/remove/$', login_required(views.landing_restaurant_remove), name='landing_restaurant_remove'),
	url(r'^backend/landing/attraction/(?P<pk>\d+)/remove/$', login_required(views.landing_attraction_remove), name='landing_attraction_remove'),
	url(r'^backend/landing/apartment/(?P<pk>\d+)/remove/$', login_required(views.landing_apartment_remove), name='landing_apartment_remove'),


	url(r'^backend/about/add_page_title$', views.about_new_pageTitle, name='about_new_pageTitle'),
	url(r'^backend/about/add_presentation$', views.about_new_presentation, name='about_new_presentation'),
	url(r'^backend/about/add_team_title$', views.about_new_teamTitle, name='about_new_teamTitle'),
	url(r'^backend/about/add_member1$', views.about_new_member1, name='about_new_member1'),
	url(r'^backend/about/add_member2$', views.about_new_member2, name='about_new_member2'),
	url(r'^backend/about/add_member3$', views.about_new_member3, name='about_new_member3'),

	url(r'^backend/about/page_title/(?P<pk>\d+)/$', views.about_pageTitle_detail, name='about_pageTitle_detail'),
	url(r'^backend/about/presentation/(?P<pk>\d+)/$', views.about_presentation_detail, name='about_presentation_detail'),
	url(r'^backend/about/team_title/(?P<pk>\d+)/$', views.about_teamTitle_detail, name='about_teamTitle_detail'),
	url(r'^backend/about/member1/(?P<pk>\d+)/$', views.about_member1_detail, name='about_memberOne_detail'),
	url(r'^backend/about/member2/(?P<pk>\d+)/$', views.about_member2_detail, name='about_memberTwo_detail'),
	url(r'^backend/about/member3/(?P<pk>\d+)/$', views.about_member3_detail, name='about_memberThree_detail'),

	url(r'^backend/about/title/(?P<pk>\d+)/edit/$', login_required(views.about_pageTitle_edit), name='about_title_edit'),
	url(r'^backend/about/presentation/(?P<pk>\d+)/edit/$', login_required(views.about_presentation_edit), name='about_presentation_edit'),
	url(r'^backend/about/team/(?P<pk>\d+)/edit/$', login_required(views.about_teamTitle_edit), name='about_teamTitle_edit'),
	url(r'^backend/about/member1/(?P<pk>\d+)/edit/$', login_required(views.about_member1_edit), name='about_member1_edit'),
	url(r'^backend/about/member2/(?P<pk>\d+)/edit/$', login_required(views.about_member2_edit), name='about_member2_edit'),
	url(r'^backend/about/member3/(?P<pk>\d+)/edit/$', login_required(views.about_member3_edit), name='about_member3_edit'),

	url(r'^backend/about/title/(?P<pk>\d+)/remove/$', login_required(views.about_pageTitle_remove), name='about_title_remove'),
	url(r'^backend/about/presentation/(?P<pk>\d+)/remove/$', login_required(views.about_presentation_remove), name='about_presentation_remove'),
	url(r'^backend/about/team/(?P<pk>\d+)/remove/$', login_required(views.about_teamTitle_remove), name='about_teamTitle_remove'),
	url(r'^backend/about/member1/(?P<pk>\d+)/remove/$', login_required(views.about_member1_remove), name='about_member1_remove'),
	url(r'^backend/about/member2/(?P<pk>\d+)/remove/$', login_required(views.about_member2_remove), name='about_member2_remove'),
	url(r'^backend/about/member3/(?P<pk>\d+)/remove/$', login_required(views.about_member3_remove), name='about_member3_remove'),


	url(r'^backend/contact/add_header$', views.contact_new_header, name='contact_new_header'),
	url(r'^backend/contact/add_information$', views.contact_new_information, name='contact_new_information'),
	url(r'^backend/contact/add_address$', views.contact_new_address, name='contact_new_address'),

	url(r'^backend/contact/header/(?P<pk>\d+)/$', views.contact_header_detail, name='contact_header_detail'),
	url(r'^backend/contact/information/(?P<pk>\d+)/$', views.contact_information_detail, name='contact_information_detail'),
	url(r'^backend/contact/address/(?P<pk>\d+)/$', views.contact_address_detail, name='contact_address_detail'),

	url(r'^backend/contact/header/(?P<pk>\d+)/edit/$', login_required(views.contact_header_edit), name='contact_header_edit'),
	url(r'^backend/contact/information/(?P<pk>\d+)/edit/$', login_required(views.contact_information_edit), name='contact_information_edit'),
	url(r'^backend/contact/address/(?P<pk>\d+)/edit/$', login_required(views.contact_address_edit), name='contact_address_edit'),

	url(r'^backend/contact/header/(?P<pk>\d+)/remove/$', login_required(views.contact_header_remove), name='contact_header_remove'),
	url(r'^backend/contact/information/(?P<pk>\d+)/remove/$', login_required(views.contact_information_remove), name='contact_information_remove'),
	url(r'^backend/contact/address/(?P<pk>\d+)/remove/$', login_required(views.contact_address_remove), name='contact_address_remove'),	


	url(r'^backend/houses/add_house$', views.house_create, name='house_create'),
	url(r'^backend/houses/detail/(?P<pk>\d+)/$', views.house_details, name='house_details'),
	url(r'^backend/houses/edit/(?P<pk>\d+)/$', views.house_edit, name='house_edit'),
	url(r'^backend/houses/remove/(?P<pk>\d+)/$', views.house_remove, name='house_remove'),


	url(r'^backend/accounts/unban/(?P<pk>\d+)/$', login_required(views.staff_unban_user), name='staff_unban_user'),
	url(r'^backend/accounts/ban/(?P<pk>\d+)/$', login_required(views.staff_ban_user), name='staff_ban_user'),
	url(r'^backend/accounts/abuse$', login_required(views.staff_accounts_abuse), name='staff_accounts_abuse'),  
    url(r'^backend/accounts/delete$', login_required(views.to_del_user), name='staff_predel_user'),  
	url(r'^backend/accounts/(?P<pk>\d+)/delete/$', login_required(views.del_user), name='del_user'),  
	url(r'^backend/staff/list/$', login_required(views.staff_list), name='staff_list'),

    url(r'^signup/$', views.signup, name='signup'),


] 

easyhome/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from appApi import views
from appApi import models


router = routers.DefaultRouter()
router.register(r'users', views.UsersViewSet)
router.register(r'deal',views.DealViewSet)
router.register(r'attractions',views.AttractionsViewSet)
router.register(r'restaurant',views.RestaurantViewSet)
router.register(r'services',views.ServicesViewSet)
router.register(r'accomodations', views.AccomodationsViewSet)
router.register(r'reviews', views.ReviewsViewSet)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('backend.urls')),
    url(r'', include('frontend.urls')),
    url(r'api/', include(router.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'', views.AccomodationsListView, name='accomodations'),
    #url(r'',views.AccomodationsListView.as_view(), name="accomodations"),
   # url(r'^api/docs/', include('rest_framework_docs.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

frontend/urls.py
from django.conf.urls import include, url
#from django.contrib.auth import views as auth_views
import backend
from . import views
from django.contrib.auth.decorators import login_required
"""from rest_framework.schemas import get_schema_view
schema_view = get_schema_view(title='Pastebin API')"""

"""url(r'^$', views.frontend_home, name='frontend_home'),"""

app_name='frontend'
urlpatterns = [
	url(r'^search/',views.pageform,name="search"),
	url(r'^searchR/',views.pageformR,name="searchR"),
	url(r'^searchA/',views.pageformA,name="searchA"),
	url(r'^single/',views.single,name="single"),
	url(r'^singleA/',views.singleA,name="singleA"),
	url(r'^singleR/',views.singleR,name="singleR"),
	url(r'^ListR/',views.listAllRestaurants,name="ListR"),
	url(r'^ListA/',views.listAllAttractions,name="ListA"),
	url(r'^ListAcc/',views.listAllAccomodations,name="listAcc"),
	url(r'^home/$', views.frontend_home, name='frontend_home'),
	#url(r'^about$', views.AboutPageView.as_view(), name='AboutPageView'),
	url(r'^about$', views.frontend_about, name='frontend_about'),
	#url(r'^contact$', views.frontend_contact, name='frontend_contact'),
	url(r'^contact$', views.frontend_contact, name='frontend_contact'),


    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/profile', views.ProfilePageView.as_view(), name='profile'),

    url(r'^api/docs/', include('rest_framework_docs.urls')),

]

frontend/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

frontend/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import redirect, render, get_object_or_404

from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils import timezone
# Create your views here.

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render,HttpResponse
from django.views.generic import TemplateView

import backend
from backend.models import *
from appApi.models import Accomodations, Restaurant, Attractions


####
## frontend Views
####


from django.views.generic import ListView
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView

def listAllAttractions(request):
    attractions = Attractions.objects.all()
    return render(request, 'frontend/listAllA.html',{"attractions":attractions})

def listAllAccomodations(request):
    accomodations = Accomodations.objects.all()
    return render(request, 'frontend/listAll.html',{"accomodations":accomodations})

def listAllRestaurants(request):
    restaurants = Restaurant.objects.all()
    return render(request, 'frontend/listAllR.html',{"restaurants":restaurants})

def single(request):
    id  = request.GET.get('id', '')
    accomodations = Accomodations.objects.all()
    return render(request,'frontend/single.html',{"id":id,"accomodations":accomodations})

def singleR(request):
    id  = request.GET.get('id', '')
    restaurants = Restaurant.objects.all()
    return render(request,'frontend/single_restaurant.html',{"id":id,"restaurants":restaurants})

def singleA(request):
    id  = request.GET.get('id', '')
    attractions = Attractions.objects.all()
    return render(request,'frontend/single_attraction.html',{"id":id,"attractions":attractions})

def pageform(request):
    name = request.GET.get('name', '')
    accomodations = Accomodations.objects.all()
    return render(request, 'frontend/list.html',{"name" : name, "accomodations":accomodations})

def pageformR(request):
    name = request.GET.get('name', '')
    restaurants = Restaurant.objects.all()
    return render(request, 'frontend/listR.html',{"name" : name, "restaurants":restaurants})

def pageformA(request):
    name = request.GET.get('name', '')
    attractions = Attractions.objects.all()
    return render(request, 'frontend/listA.html',{"name" : name, "attractions":attractions})

# class AccomodationsListView(ListView):
#     model = Accomodations
#     template_name = 'frontend/home.html'
#     context_object_name = 'accomodations'

def frontend_home(request):
	restaurants = Restaurants.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	attractions = Attractions.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	apartments = Apartments.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	return render(request, 'frontend/home.html', {'restaurants': restaurants, 'attractions': attractions, 'apartments':apartments})

def frontend_about(request):
	pageTitles = About_PageTitle.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	presentations = About_PresentationText.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	teams = About_TeamTitle.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	memberones = About_MemberOne.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	membertwos = About_MemberTwo.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	memberthrees = About_MemberThree.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	return render(request, 'frontend/about.html', {'pageTitles': pageTitles, 'presentations': presentations, 'teams':teams, 'memberones':memberones, 'membertwos':membertwos, 'memberthrees':memberthrees})

def frontend_home(request):
	restaurants = Restaurants.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	attractions = Attractions.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	apartments = Apartments.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	return render(request, 'frontend/home.html', {'restaurants': restaurants, 'attractions': attractions, 'apartments':apartments})

def frontend_about(request):
	pageTitles = About_PageTitle.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	presentations = About_PresentationText.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	teams = About_TeamTitle.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	memberones = About_MemberOne.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	membertwos = About_MemberTwo.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	memberthrees = About_MemberThree.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	return render(request, 'frontend/about.html', {'pageTitles': pageTitles, 'presentations': presentations, 'teams':teams, 'memberones':memberones, 'membertwos':membertwos, 'memberthrees':memberthrees})

def frontend_contact(request):
	headers = Contact_Header.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	informations = Contact_Information.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	addresses = Contact_Address.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	return render(request, 'frontend/contact.html', {'headers': headers, 'informations': informations, 'addresses':addresses})

class ProfilePageView(TemplateView):
 	template_name = "frontend/profile.html"

class LogoutPageView(TemplateView):
 	template_name = "registration/logged_out.html"

frontend/templates/frontend/about.html
{% extends 'frontend/index.html' %}
{% load staticfiles %}

{% block content %}
<section id="main">
<!--header strip end here-->
<!--about start here-->
<div class="about">
	<div class="container">
		<div class="about-main">
			<!-- <h4>About us</h4> -->
			{% for pageTitle in pageTitles %}
				<h4>{{ pageTitle.title }}</h4>
			{% endfor %}
			<div class="col-md-6 about-left">
				<a href="#"><img src="{% static '../static/images/ab.jpg' %}" alt="" class="img-responsive"></a>
			</div>
			<div class="col-md-6 about-rigth">
				{% for presentation in presentations %}
				<h3><a href="single.html">{{ presentation.title }}</a></h3>
				<p>{{ presentation.text|linebreaksbr }}</p>
				{% endfor %}
			</div>
		  <div class="clearfix"> </div>
		</div>
	</div>
</div>
<!--about end here-->
<!--about team start here-->
<div class="team">
	<div class="container">
		<div class="team-main">
			{% for team in teams %}
				<h4>{{ team.title }}</h4>
			{% endfor %}
			<div class="col-md-3 team-grid">
				<img src="{% static '../static/images/t1.jpg' %}" alt="" class="img-responsive">
				{% for memberone in memberones %}
				<h3><a class="popup-with-zoom-anim" href="#small-dialog">{{ memberone.title }}</a></h3>
				<p>{{ memberone.text|linebreaksbr }}</p>
				{% endfor %}
			</div>
			<div class="col-md-3 team-grid">
				<img src="{% static '../static/images/t2.jpg' %}" alt="" class="img-responsive">
				{% for membertwo in membertwos %}
				<h3><a class="popup-with-zoom-anim" href="#small-dialog">{{ membertwo.title }}</a></h3>
				<p>{{ membertwo.text|linebreaksbr }}</p>
				{% endfor %}
			</div>
			<div class="col-md-3 team-grid">
				<img src="{% static '../static/images/t3.jpg' %}" alt="" class="img-responsive">
				{% for memberthree in memberthrees %}
				<h3><a class="popup-with-zoom-anim" href="#small-dialog">{{ memberthree.title }}</a></h3>
				<p>{{ memberthree.text|linebreaksbr }}</p>
				{% endfor %}
			</div>
			<div class="col-md-3 team-grid">
				<img src="{% static '../static/images/t4.jpg' %}" alt="" class="img-responsive">
				<h3><a class="popup-with-zoom-anim" href="#small-dialog">Ming Yuan</a></h3>
				<p>She is from China and loves to write.</p>
			</div>
		</div>
	</div>
</div>

{% endblock %}

frontend/templates/frontend/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>EasyHouse | Travel made easy</title>

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<script src="https://code.jquery.com/jquery-latest.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">


	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="{% static '../static/js/jquery-1.11.0.min.js' %}"></script>
	<!-- Custom Theme files -->
	<link href="{% static '../static/css/styleFront.css' %}" rel="stylesheet" type="text/css" media="all"/>
	<link href="{% static '../static/css/hover.css' %}" rel="stylesheet" media="all">
	<!-- Custom Theme files -->

	<meta name="keywords" content="EasyHouse" />

	<!--Google Fonts-->
	<link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
	<link href='//fonts.googleapis.com/css?family=Hind:400,300,500,600,700' rel='stylesheet' type='text/css'>


</head>
<body>
<!--header banner start here-->
<nav class="navbar-default navbar navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			<a class="navbar-brand" href="{% url 'accomodations' %}">Easy Home</a>
			</div>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav">
					<!-- <li><a id="home" href="/"><span class="glyphicon glyphicon-home"></span></a></li> -->
					<li><a id="" href="{% url 'frontend:listAcc' %}"><i class="fa fa-bed fa-lg"></i> Accomodations</a></li>
					<li><a id="" href="{% url 'frontend:ListR' %}"><i class="fa fa-cutlery fa-lg "></i> Restaurants</a></li>
					<li><a id="" href="{% url 'frontend:ListA' %}"><i class="fa fa-camera-retro fa-lg"></i> Attractions</a></li>

					<li><a style="color:red;pointer-events: none; cursor: default;" id="" href=""><i style="color:red" class="fa fa-heart-o fa-lg"></i> Deals</a></li>
				</ul>

				{% if user.is_authenticated %}
					<ul class="nav navbar-nav navbar-right">
						<li><a id="contact-form" href="{% url 'frontend:frontend_contact' %}"><i class="fa fa-envelope-o fa-lg"></i> Contact</a></li>
						<li><a id="about" href="{% url 'frontend:frontend_about' %}"><i class="fa fa-question-circle-o fa-lg"></i> About</a></li>
						<li><a id="login" href="{% url 'backend:backend_home' %}"><i class="fa fa-cogs fa-lg"></i> Backend</a></li>
						<li><a id="login" href="{% url 'frontend:logout' %}?next={% url 'accomodations' %}"><i class="fa fa-sign-out fa-lg"></i> Log out</a></li>
					</ul>
				{% else %}
					<ul class="nav navbar-nav navbar-right">
						<li><a id="contact-form" href="{% url 'frontend:frontend_contact' %}"><i class="fa fa-envelope-o fa-lg"></i> Contact</a></li>
						<li><a id="about" href="{% url 'frontend:frontend_about' %}"><i class="fa fa-question-circle-o fa-lg"></i> About</a></li>
						<li><a id="signup" class="btn" href="{% url 'backend:signup' %}"><i class="fa fa-user-plus fa-lg"></i> Sign Up</a></li>
						<li><a id="login" href="{% url 'frontend:login' %}?next={% url 'accomodations' %}"><i class="fa fa-sign-in fa-lg"></i> Login</a></li>
					</ul>
				{% endif %}

			</div>
		</div>
	</nav>
<section id="main">
<!--header strip end here-->
<!--contant start here-->
{% block content %}
{% endblock %}
<!--map end here-->
<footer>
		<div class="container">
			<div class="row">
				<div style="color:white" class="col-sm-4 paddingtop-bottom info-footer">
					<div class="logofooter">Easy House</div>
					<p>Travel made easy</p>
					<p><i class="fa fa-map-pin"></i> TU/e 5612 AZ Eindhoven</p>
					<p><i class="fa fa-phone"></i> Phone (NL) : +31 040 247 9111</p>
					<p><i class="fa fa-envelope"></i> E-mail : easyhouse@tue.nl</p>
				</div>
				<div class="col-sm-4 paddingtop-bottom">
					<h6 class="heading7">GENERAL LINKS</h6>
					<ul class="footer-ul">
						<li><a href="{% url 'frontend:frontend_about' %}">Meet the team</a></li>
						<li><a href="#">Privacy Policy</a></li>
						<li><a href="#">Terms & Conditions</a></li>
						<li><a href="#">Frequently Ask Questions</a></li>
					</ul>
				</div>
				<div class="col-sm-4 paddingtop-bottom">
					<h6 class="heading7">LATEST POST</h6>
					<div class="post">
						<p>Generated automatically parsing news through some API, to implement yet  <span>December 5,2017</span></p>
						<p>Generated automatically parsing news through some API, to implement yet  <span>October 30,2017</span></p>
						<p>Generated automatically parsing news through some API, to implement yet  <span>July 24,2017</span></p>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<div class="copyright">
		<div class="container">
			<div class="col-md-6">
				<p><span id="license">&copy; 2018 - Easy House - Travel made easy</span></p>
			</div>
			<div class="col-md-6">
				<ul class="bottom_ul">
					<li><a href="#">Easy Home</a></li>
					<li><a href="{% url 'frontend:frontend_about' %}">About us</a></li>
					<li><a href="#">Blog</a></li>
					<li><a href="#">Community</a></li>
					<li><a id="fContact" href="{% url 'frontend:frontend_contact' %}">Contact us</a></li>
					<li><a href="https://tue.nl" target="_blank">TU/e</a></li>
				</ul>
			</div>
		</div>
	</div>
</body>
</html>

frontend/templates/frontend/signup.html
{% extends 'frontend/index.html' %}

{% load staticfiles %}
{% block content %}

<link href="{% static '../static/css/signup_style.css' %}" rel="stylesheet">

<div class="form">
  <ul class="tab-group">
    <li class="tab active"><a href="{% url 'backend:signup' %}">Sign Up</a></li>
    <li class="tab"><a href="{% url 'frontend:login' %}">Log In</a></li>
  </ul>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button" type="submit">Sign up</button>
  </form>
</div>

{% endblock %}