backend/urls.py
from django.conf.urls import include, url
#from django.contrib.auth import views as auth_views
import frontend
from . import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.decorators import login_required

app_name = 'backend'
urlpatterns = [
	url(r'^backend/$', views.backend_home, name='backend_home'),
	url(r'^backend/operations$', views.OperationsPageView.as_view(), name='operations'),
	url(r'^backend/operations/restaurants$', views.backend_ops_restaurants_PageView.as_view(), name='backend_ops_restaurants'),
	url(r'^backend/operations/attractions$', views.backend_ops_attractions_PageView.as_view(), name='backend_ops_attractions'),
	url(r'^backend/operations/apartments$', views.backend_ops_apartments, name='backend_ops_apartments'),
	url(r'^backend/operations/landing$', views.backend_ops_landing, name='backend_ops_landing'),
	url(r'^backend/operations/about$', views.backend_ops_about, name='backend_ops_about'),
	url(r'^backend/operations/contact$', views.backend_ops_contact, name='backend_ops_contact'),
	url(r'^backend/operations/users$', views.staff_accounts_abuse, name='staff_accounts_abuse'),
	# url(r'^backend/operations/landing$', views.backend_ops_landing_PageView.as_view(), name='backend_ops_landing'),
	# url(r'^backend/operations/contact$', views.backend_ops_contact_PageView.as_view(), name='backend_ops_contact'),
	# url(r'^backend/operations/about$', views.backend_ops_about_PageView.as_view(), name='backend_ops_about'),
	# url(r'^backend/operations/deals$', views.backend_ops_apartments_PageView.as_view(), name='backend_ops_deals'),
	# url(r'^backend/operations/apartments$', views.backend_ops_apartments_PageView.as_view(), name='backend_ops_apartments'),


	url(r'^backend/landing/add_restaurant$', views.landing_new_restaurant, name='landing_new_restaurant'),
	url(r'^backend/landing/add_attraction$', views.landing_new_attraction, name='landing_new_attraction'),
	url(r'^backend/landing/add_apartment$', views.landing_new_apartment, name='landing_new_apartment'),

	url(r'^backend/landing/restaurant/(?P<pk>\d+)/$', views.landing_restaurant_detail, name='landing_restaurant_detail'),
	url(r'^backend/landing/attraction/(?P<pk>\d+)/$', views.landing_attraction_detail, name='landing_attraction_detail'),
	url(r'^backend/landing/apartment/(?P<pk>\d+)/$', views.landing_apartment_detail, name='landing_apartment_detail'),

    url(r'^backend/landing/restaurants/(?P<pk>\d+)/edit/$', login_required(views.landing_restaurant_edit), name='landing_restaurant_edit'),
    url(r'^backend/landing/attraction/(?P<pk>\d+)/edit/$', login_required(views.landing_attraction_edit), name='landing_attraction_edit'),
    url(r'^backend/landing/apartment/(?P<pk>\d+)/edit/$', login_required(views.landing_apartment_edit), name='landing_apartment_edit'),

	url(r'^backend/landing/restaurants/(?P<pk>\d+)/remove/$', login_required(views.landing_restaurant_remove), name='landing_restaurant_remove'),
	url(r'^backend/landing/attraction/(?P<pk>\d+)/remove/$', login_required(views.landing_attraction_remove), name='landing_attraction_remove'),
	url(r'^backend/landing/apartment/(?P<pk>\d+)/remove/$', login_required(views.landing_apartment_remove), name='landing_apartment_remove'),


	url(r'^backend/about/add_page_title$', views.about_new_pageTitle, name='about_new_pageTitle'),
	url(r'^backend/about/add_presentation$', views.about_new_presentation, name='about_new_presentation'),
	url(r'^backend/about/add_team_title$', views.about_new_teamTitle, name='about_new_teamTitle'),
	url(r'^backend/about/add_member1$', views.about_new_member1, name='about_new_member1'),
	url(r'^backend/about/add_member2$', views.about_new_member2, name='about_new_member2'),
	url(r'^backend/about/add_member3$', views.about_new_member3, name='about_new_member3'),

	url(r'^backend/about/page_title/(?P<pk>\d+)/$', views.about_pageTitle_detail, name='about_pageTitle_detail'),
	url(r'^backend/about/presentation/(?P<pk>\d+)/$', views.about_presentation_detail, name='about_presentation_detail'),
	url(r'^backend/about/team_title/(?P<pk>\d+)/$', views.about_teamTitle_detail, name='about_teamTitle_detail'),
	url(r'^backend/about/member1/(?P<pk>\d+)/$', views.about_member1_detail, name='about_memberOne_detail'),
	url(r'^backend/about/member2/(?P<pk>\d+)/$', views.about_member2_detail, name='about_memberTwo_detail'),
	url(r'^backend/about/member3/(?P<pk>\d+)/$', views.about_member3_detail, name='about_memberThree_detail'),

	url(r'^backend/about/title/(?P<pk>\d+)/edit/$', login_required(views.about_pageTitle_edit), name='about_title_edit'),
	url(r'^backend/about/presentation/(?P<pk>\d+)/edit/$', login_required(views.about_presentation_edit), name='about_presentation_edit'),
	url(r'^backend/about/team/(?P<pk>\d+)/edit/$', login_required(views.about_teamTitle_edit), name='about_teamTitle_edit'),
	url(r'^backend/about/member1/(?P<pk>\d+)/edit/$', login_required(views.about_member1_edit), name='about_member1_edit'),
	url(r'^backend/about/member2/(?P<pk>\d+)/edit/$', login_required(views.about_member2_edit), name='about_member2_edit'),
	url(r'^backend/about/member3/(?P<pk>\d+)/edit/$', login_required(views.about_member3_edit), name='about_member3_edit'),

	url(r'^backend/about/title/(?P<pk>\d+)/remove/$', login_required(views.about_pageTitle_remove), name='about_title_remove'),
	url(r'^backend/about/presentation/(?P<pk>\d+)/remove/$', login_required(views.about_presentation_remove), name='about_presentation_remove'),
	url(r'^backend/about/team/(?P<pk>\d+)/remove/$', login_required(views.about_teamTitle_remove), name='about_teamTitle_remove'),
	url(r'^backend/about/member1/(?P<pk>\d+)/remove/$', login_required(views.about_member1_remove), name='about_member1_remove'),
	url(r'^backend/about/member2/(?P<pk>\d+)/remove/$', login_required(views.about_member2_remove), name='about_member2_remove'),
	url(r'^backend/about/member3/(?P<pk>\d+)/remove/$', login_required(views.about_member3_remove), name='about_member3_remove'),


	url(r'^backend/contact/add_header$', views.contact_new_header, name='contact_new_header'),
	url(r'^backend/contact/add_information$', views.contact_new_information, name='contact_new_information'),
	url(r'^backend/contact/add_address$', views.contact_new_address, name='contact_new_address'),

	url(r'^backend/contact/header/(?P<pk>\d+)/$', views.contact_header_detail, name='contact_header_detail'),
	url(r'^backend/contact/information/(?P<pk>\d+)/$', views.contact_information_detail, name='contact_information_detail'),
	url(r'^backend/contact/address/(?P<pk>\d+)/$', views.contact_address_detail, name='contact_address_detail'),

	url(r'^backend/contact/header/(?P<pk>\d+)/edit/$', login_required(views.contact_header_edit), name='contact_header_edit'),
	url(r'^backend/contact/information/(?P<pk>\d+)/edit/$', login_required(views.contact_information_edit), name='contact_information_edit'),
	url(r'^backend/contact/address/(?P<pk>\d+)/edit/$', login_required(views.contact_address_edit), name='contact_address_edit'),

	url(r'^backend/contact/header/(?P<pk>\d+)/remove/$', login_required(views.contact_header_remove), name='contact_header_remove'),
	url(r'^backend/contact/information/(?P<pk>\d+)/remove/$', login_required(views.contact_information_remove), name='contact_information_remove'),
	url(r'^backend/contact/address/(?P<pk>\d+)/remove/$', login_required(views.contact_address_remove), name='contact_address_remove'),	


	url(r'^backend/houses/add_house$', views.house_create, name='house_create'),
	url(r'^backend/houses/detail/(?P<pk>\d+)/$', views.house_details, name='house_details'),
	url(r'^backend/houses/edit/(?P<pk>\d+)/$', views.house_edit, name='house_edit'),
	url(r'^backend/houses/remove/(?P<pk>\d+)/$', views.house_remove, name='house_remove'),


	url(r'^backend/accounts/unban/(?P<pk>\d+)/$', login_required(views.staff_unban_user), name='staff_unban_user'),
	url(r'^backend/accounts/ban/(?P<pk>\d+)/$', login_required(views.staff_ban_user), name='staff_ban_user'),
	url(r'^backend/accounts/abuse$', login_required(views.staff_accounts_abuse), name='staff_accounts_abuse'),  
    url(r'^backend/accounts/delete$', login_required(views.to_del_user), name='staff_predel_user'),  
	url(r'^backend/accounts/(?P<pk>\d+)/delete/$', login_required(views.del_user), name='del_user'),  
	url(r'^backend/staff/list/$', login_required(views.staff_list), name='staff_list'),

    url(r'^signup/$', views.signup, name='signup'),


] 

easyhome/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from appApi import views
from appApi import models


router = routers.DefaultRouter()
router.register(r'users', views.UsersViewSet)
router.register(r'deal',views.DealViewSet)
router.register(r'attractions',views.AttractionsViewSet)
router.register(r'restaurant',views.RestaurantViewSet)
router.register(r'services',views.ServicesViewSet)
router.register(r'accomodations', views.AccomodationsViewSet)
router.register(r'reviews', views.ReviewsViewSet)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('backend.urls')),
    url(r'', include('frontend.urls')),
    url(r'api/', include(router.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'', views.AccomodationsListView, name='accomodations'),
    #url(r'',views.AccomodationsListView.as_view(), name="accomodations"),
   # url(r'^api/docs/', include('rest_framework_docs.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver

from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField

class Attractions(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	text = models.TextField()
	#text = RichTextUploadingField()
	created_date = models.DateTimeField(
			default=timezone.now)
	published_date = models.DateTimeField(
			blank=True, null=True)

class Restaurants(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	text = models.TextField()
	#text = RichTextUploadingField()
	created_date = models.DateTimeField(
			default=timezone.now)
	published_date = models.DateTimeField(
			blank=True, null=True)

class Apartments(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	text = models.TextField()
	#text = RichTextUploadingField()
	created_date = models.DateTimeField(
			default=timezone.now)
	published_date = models.DateTimeField(
			blank=True, null=True)

class About_PageTitle(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	created_date = models.DateTimeField(
			default=timezone.now)
	published_date = models.DateTimeField(
			blank=True, null=True)

class About_PresentationText(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	text = models.TextField()
	#text = RichTextUploadingField()
	created_date = models.DateTimeField(
			default=timezone.now)
	published_date = models.DateTimeField(
			blank=True, null=True)

class About_TeamTitle(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	created_date = models.DateTimeField(
			default=timezone.now)
	published_date = models.DateTimeField(
			blank=True, null=True)

class About_MemberOne(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	text = models.TextField()
	#text = RichTextUploadingField()
	created_date = models.DateTimeField(
			default=timezone.now)
	published_date = models.DateTimeField(
			blank=True, null=True)

class About_MemberTwo(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	text = models.TextField()
	#text = RichTextUploadingField()
	created_date = models.DateTimeField(
			default=timezone.now)
	published_date = models.DateTimeField(
			blank=True, null=True)

class About_MemberThree(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	text = models.TextField()
	#text = RichTextUploadingField()
	created_date = models.DateTimeField(
			default=timezone.now)
	published_date = models.DateTimeField(
			blank=True, null=True)

class Contact_Header(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	text = models.TextField()
	#text = RichTextUploadingField()
	created_date = models.DateTimeField(
			default=timezone.now)
	published_date = models.DateTimeField(
			blank=True, null=True)

class Contact_Information(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	text = models.TextField()
	#text = RichTextUploadingField()
	created_date = models.DateTimeField(
			default=timezone.now)
	published_date = models.DateTimeField(
			blank=True, null=True)

class Contact_Address(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	text = models.TextField()
	#text = RichTextUploadingField()
	created_date = models.DateTimeField(
			default=timezone.now)
	published_date = models.DateTimeField(
			blank=True, null=True)

class House_User(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	#description = models.TextField()
	description = RichTextUploadingField()
	city = models.CharField(max_length=200)
	price = models.CharField(max_length=200)
	created_date = models.DateTimeField(
			default=timezone.now)
	published_date = models.DateTimeField(
			blank=True, null=True)

# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     bio = models.TextField(max_length=500, blank=True)
#     location = models.CharField(max_length=30, blank=True)
#     birth_date = models.DateField(null=True, blank=True)

# @receiver(post_save, sender=User)
# def update_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#     instance.profile.save()

# 	def publish(self):
# 		self.published_date = timezone.now()
# 		self.save()

# 	def __unicode__(self):
# 		return self.title
# 	#def __str__(self):
# 	#    return self.title

backend/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

#from ckeditor_uploader.widgets import CKEditorUploadingWidget

from .models import Attractions, Restaurants, Apartments, About_PageTitle, About_PresentationText, About_TeamTitle, About_MemberOne, About_MemberTwo, About_MemberThree, Contact_Header, Contact_Information, Contact_Address, House_User

# class PostNewHouse(forms.ModelForm):
#     # content = forms.CharField(widget=CKEditorUploadingWidget())
#     # Reminder: add some extra requirement before meta?
#     class Meta:
#         model = House_Creation
#         fields = ('title', 'description', 'city', 'price')

class PostHouse(forms.ModelForm):

    class Meta:
        model = House_User
        fields = ('title', 'description', 'city', 'price')

class SignUpForm(UserCreationForm):

    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    location = forms.CharField(max_length=30, required=False, help_text='Optional.')
    postal = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'location', 'postal', 'email', 'password1', 'password2', )

class PostAttraction(forms.ModelForm):

    class Meta:
        model = Attractions
        fields = ('title', 'text',)

class PostRestaurant(forms.ModelForm):

    class Meta:
        model = Restaurants
        fields = ('title', 'text',)

class PostApartment(forms.ModelForm):

    class Meta:
        model = Apartments
        fields = ('title', 'text',)

class PostAboutTitle(forms.ModelForm):

    class Meta:
        model = About_PageTitle
        fields = ('title',)

class PostAboutPresentation(forms.ModelForm):

    class Meta:
        model = About_PresentationText
        fields = ('title', 'text',)

class PostAboutTeamTitle(forms.ModelForm):

    class Meta:
        model = About_TeamTitle
        fields = ('title',)

class PostAboutMemberOne(forms.ModelForm):

    class Meta:
        model = About_MemberOne
        fields = ('title', 'text',)

class PostAboutMemberTwo(forms.ModelForm):

    class Meta:
        model = About_MemberTwo
        fields = ('title', 'text',)

class PostAboutMemberThree(forms.ModelForm):

    class Meta:
        model = About_MemberThree
        fields = ('title', 'text',)

class PostContactHeader(forms.ModelForm):

    class Meta:
        model = Contact_Header
        fields = ('title', 'text',)

class PostContactInformation(forms.ModelForm):

    class Meta:
        model = Contact_Information
        fields = ('title', 'text',)

class PostContactAddress(forms.ModelForm):

    class Meta:
        model = Contact_Address
        fields = ('title', 'text',)

backend/templates/backend/about_member1_detail.html
{% extends 'backend/backend.html' %}
{% load staticfiles %}

{% block content %}
 <div class="section">
        {% if section.published_date %}
            <div class="date">
                {{ section.published_date }}
            </div>
        {% endif %}
        <a class="btn btn-default" href="{% url 'backend:about_member1_edit' pk=section.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-default" href="{% url 'backend:about_member1_remove' pk=section.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        <h1>{{ section.title }}</h1>
        <p>{{ section.text|linebreaksbr }}</p>		
</div>
<p><a href="{% url 'backend:backend_ops_about' %}">Back to the list</a></p>
{% endblock %}

backend/templates/backend/about_pageTitle_new.html
{% extends 'backend/backend.html' %}
{% load staticfiles %}

{% block content %}

<div class="section">
	 <h1>Create new about us page title</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
</div>

{% endblock %}

backend/templates/backend/backend_ops_about.html
{% extends 'backend/backend.html' %}
{% load staticfiles %}

{% block content %}
<link href="{% static '../static/css/backendStyle.css' %}" rel="stylesheet">    
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container-fluid">
        <!-- center left-->
        <h3>About Page</h3>
        <hr>
        <h4>Add content</h4>
        <div class="col-xs-12 col-sm-12 col-lg-12">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="div-square">
              <a href="{% url 'backend:about_new_pageTitle' %}">
                <i class="fa fa-thumb-tack fa-3x"></i>
                <h5><strong>Page Title</strong></h5>
              </a>
            </div>
          </div>

          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="div-square">
              <a href="{% url 'backend:about_new_presentation' %}">
                <i class="fa fa-info fa-3x"></i>
                <h5><strong>Presentation</strong> section</h5>
              </a>
            </div>
          </div>

          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="div-square">
              <a href="{% url 'backend:about_new_teamTitle' %}">
                <i class="fa fa-thumb-tack fa-3x"></i>
                <h5><strong>Team Title</strong></h5>
              </a>
            </div>
          </div>

          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <div class="div-square">
              <a href="{% url 'backend:about_new_member1' %}">
                <i class="fa fa-user fa-3x"></i>
                <h5><strong>Member 1</strong> column</h5>
              </a>
            </div>
          </div>

          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <div class="div-square">
              <a href="{% url 'backend:about_new_member2' %}">
                <i class="fa fa-user fa-3x"></i>
                <h5><strong>Member 2</strong> column</h5>
              </a>
            </div>
          </div>

          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <div class="div-square">
              <a href="{% url 'backend:about_new_member3' %}">
                <i class="fa fa-user fa-3x"></i>
                <h5><strong>Member 3</strong> column</h5>
              </a>
            </div>
          </div>

</div>
<p> &nbsp;</p>
<hr>

<h4>Title's section</h4>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Date</th>
      <th scope="col">Publisher</th>
      <th scope="col">Operations</th>
    </tr>
  </thead>
  <tbody>
    {% for title in titles %}
    <tr>
      <th scope="row">{{ title.pk }}</th>
      <td><a href="{% url 'backend:about_pageTitle_detail' pk=title.pk %}">{{ title.title }}</td>
      <td>{{ title.published_date }}</td>
      <td>@{{ title.author }}</td>
      <td> <a class="glyphicon glyphicon-pencil" alt="Edit {{ title.title }}" href="{% url 'backend:about_title_edit' pk=title.pk %}"></a>
        <a class="glyphicon glyphicon-trash" href="{% url 'backend:about_title_remove' pk=title.pk %}"></a></td>
    </tr>
    {% endfor %}
</table>

<h4>Presentation's section</h4>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Date</th>
      <th scope="col">Publisher</th>
      <th scope="col">Operations</th>
    </tr>
  </thead>
  <tbody>
    {% for presentation in presentations %}
    <tr>
      <th scope="row">{{ presentation.pk }}</th>
      <td><a href="{% url 'backend:about_presentation_detail' pk=presentation.pk %}">{{ presentation.title }}</td>
      <td>{{ presentation.published_date }}</td>
      <td>@{{ presentation.author }}</td>
      <td> <a class="glyphicon glyphicon-pencil" alt="Edit {{ presentation.title }}" href="{% url 'backend:about_presentation_edit' pk=presentation.pk %}"></a>
        <a class="glyphicon glyphicon-trash" href="{% url 'backend:about_presentation_remove' pk=presentation.pk %}"></a></td>
    </tr>
    {% endfor %}
</table>

<h4>Team's title</h4>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Date</th>
      <th scope="col">Publisher</th>
      <th scope="col">Operations</th>
    </tr>
  </thead>
  <tbody>
    {% for team in teams %}
    <tr>
      <th scope="row">{{ team.pk }}</th>
      <td><a href="{% url 'backend:about_teamTitle_detail' pk=team.pk %}">{{ team.title }}</td>
      <td>{{ team.published_date }}</td>
      <td>@{{ team.author }}</td>
      <td> <a class="glyphicon glyphicon-pencil" alt="Edit {{ team.title }}" href="{% url 'backend:about_teamTitle_edit' pk=team.pk %}"></a>
        <a class="glyphicon glyphicon-trash" href="{% url 'backend:about_teamTitle_remove' pk=team.pk %}"></a></td>
    </tr>
    {% endfor %}
</table>

<h4>Member 1's title</h4>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Date</th>
      <th scope="col">Publisher</th>
      <th scope="col">Operations</th>
    </tr>
  </thead>
  <tbody>
    {% for memberone in memberones %}
    <tr>
      <th scope="row">{{ memberone.pk }}</th>
      <td><a href="{% url 'backend:about_memberOne_detail' pk=memberone.pk %}">{{ memberone.title }}</td>
      <td>{{ memberone.published_date }}</td>
      <td>@{{ memberone.author }}</td>
      <td> <a class="glyphicon glyphicon-pencil" alt="Edit {{ memberone.title }}" href="{% url 'backend:about_member1_edit' pk=memberone.pk %}"></a>
        <a class="glyphicon glyphicon-trash" href="{% url 'backend:about_member1_remove' pk=memberone.pk %}"></a></td>
    </tr>
    {% endfor %}
</table>

<h4>Member 2's title</h4>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Date</th>
      <th scope="col">Publisher</th>
      <th scope="col">Operations</th>
    </tr>
  </thead>
  <tbody>
    {% for membertwo in membertwos %}
    <tr>
      <th scope="row">{{ membertwo.pk }}</th>
      <td><a href="{% url 'backend:about_memberTwo_detail' pk=membertwo.pk %}">{{ membertwo.title }}</td>
      <td>{{ membertwo.published_date }}</td>
      <td>@{{ membertwo.author }}</td>
      <td> <a class="glyphicon glyphicon-pencil" alt="Edit {{ membertwo.title }}" href="{% url 'backend:about_member2_edit' pk=membertwo.pk %}"></a>
        <a class="glyphicon glyphicon-trash" href="{% url 'backend:about_member2_remove' pk=membertwo.pk %}"></a></td>
    </tr>
    {% endfor %}
</table>

<h4>Member 3's title</h4>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Date</th>
      <th scope="col">Publisher</th>
      <th scope="col">Operations</th>
    </tr>
  </thead>
  <tbody>
    {% for memberthree in memberthrees %}
    <tr>
      <th scope="row">{{ memberthree.pk }}</th>
      <td><a href="{% url 'backend:about_memberThree_detail' pk=memberthree.pk %}">{{ memberthree.title }}</td>
      <td>{{ memberthree.published_date }}</td>
      <td>@{{ memberthree.author }}</td>
      <td> <a class="glyphicon glyphicon-pencil" alt="Edit {{ memberthree.title }}" href="{% url 'backend:about_member3_edit' pk=memberthree.pk %}"></a>
        <a class="glyphicon glyphicon-trash" href="{% url 'backend:about_member3_remove' pk=memberthree.pk %}"></a></td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

backend/templates/backend/contact_address_detail.html
{% extends 'backend/backend.html' %}
{% load staticfiles %}

{% block content %}
 <div class="section">
        {% if section.published_date %}
            <div class="date">
                {{ section.published_date }}
            </div>
        {% endif %}
        <a class="btn btn-default" href="{% url 'backend:contact_address_edit' pk=section.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-default" href="{% url 'backend:contact_address_remove' pk=section.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        <h1>{{ section.title }}</h1>
        <p>{{ section.text|linebreaksbr }}</p>
</div>
<p><a href="{% url 'backend:backend_ops_contact' %}">Back to the list</a></p>
{% endblock %}